MERCADONA_CATEGORIES = [
    {"id": "fruta-verdura", "name": "Fruta y Verdura", "emoji": "🥑", "color": "#16a34a", "order": 1, "description": "Entrada y frescos"},
    {"id": "horno-pan", "name": "Panadería y Horno", "emoji": "🥖", "color": "#d97706", "order": 2, "description": "Pan del día, bollería y empanadas"},
    {"id": "charcuteria-quesos", "name": "Charcutería y Quesos", "emoji": "🧀", "color": "#ea580c", "order": 3, "description": "Jamón, embutidos y quesos"},
    {"id": "carne", "name": "Carnicería", "emoji": "🥩", "color": "#dc2626", "order": 4, "description": "Bandejas y carnes frescas"},
    {"id": "pescado", "name": "Pescadería", "emoji": "🐟", "color": "#0284c7", "order": 5, "description": "Pescado fresco y marisco"},
    {"id": "lacteos-huevos", "name": "Lácteos, Yogures y Huevos", "emoji": "🥛", "color": "#0d9488", "order": 6, "description": "Leches, yogures +Proteínas, mantequillas"},
    {"id": "despensa-conservas", "name": "Despensa, Pasta y Aceites", "emoji": "🥫", "color": "#ca8a04", "order": 7, "description": "Aceite de oliva, legumbres, arroz, salsas"},
    {"id": "aperitivos-dulces", "name": "Aperitivos y Chocolates", "emoji": "🍫", "color": "#9333ea", "order": 8, "description": "Frutos secos, patatas, galletas Hacendado"},
    {"id": "bebidas", "name": "Bebidas y Aguas", "emoji": "🧃", "color": "#2563eb", "order": 9, "description": "Zumos frescos, refrescos, cervezas, vino"},
    {"id": "congelados", "name": "Congelados y Helados", "emoji": "🧊", "color": "#06b6d4", "order": 10, "description": "Verduras congeladas, pescados, pizzas, helados"},
    {"id": "limpieza", "name": "Limpieza del Hogar (Bosque Verde)", "emoji": "🧹", "color": "#059669", "order": 11, "description": "Detergentes, friegasuelos, papel cocina"},
    {"id": "perfumeria", "name": "Perfumería y Cuidado (Deliplus)", "emoji": "🧴", "color": "#db2777", "order": 12, "description": "Geles, champús, cremas faciales, toallitas"},
    {"id": "mascotas", "name": "Mascotas (Compy)", "emoji": "🐾", "color": "#7c3aed", "order": 13, "description": "Pienso perro, gato y snacks"},
    {"id": "otros", "name": "Varios y Bazar", "emoji": "🛒", "color": "#64748b", "order": 14, "description": "Pilas, bolsas y otros artículos"}
]

POPULAR_CATALOG = [
    {"id": "cat-1", "name": "Aguacates listos para comer", "categoryId": "fruta-verdura", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 2.89, "popular": True},
    {"id": "cat-2", "name": "Plátano de Canarias", "categoryId": "fruta-verdura", "brand": "General", "defaultUnit": "kg", "typicalPrice": 2.29, "popular": True},
    {"id": "cat-3", "name": "Tomates cherry pera", "categoryId": "fruta-verdura", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 1.65, "popular": True},
    {"id": "cat-4", "name": "Bolsa Ensalada 4 Estaciones", "categoryId": "fruta-verdura", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 0.99, "popular": True},
    {"id": "cat-5", "name": "Limones malla", "categoryId": "fruta-verdura", "brand": "Hacendado", "defaultUnit": "kg", "typicalPrice": 1.79, "popular": False},
    {"id": "cat-6", "name": "Pan de molde 100% integral sin corteza", "categoryId": "horno-pan", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.35, "popular": True},
    {"id": "cat-7", "name": "Barra de pan rústica recién horneada", "categoryId": "horno-pan", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 0.65, "popular": True},
    {"id": "cat-8", "name": "Picos camperos", "categoryId": "horno-pan", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.10, "popular": False},
    {"id": "cat-9", "name": "Empanada de atún", "categoryId": "horno-pan", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 4.20, "popular": False},
    {"id": "cat-10", "name": "Leche Semidesnatada Brick", "categoryId": "lacteos-huevos", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 4.94, "popular": True},
    {"id": "cat-11", "name": "Yogur +Proteínas Arándanos 0%", "categoryId": "lacteos-huevos", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 1.60, "popular": True},
    {"id": "cat-12", "name": "Huevos Camperos Clase L", "categoryId": "lacteos-huevos", "brand": "Hacendado", "defaultUnit": "docena", "typicalPrice": 3.35, "popular": True},
    {"id": "cat-13", "name": "Queso fresco batido 0%", "categoryId": "lacteos-huevos", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.30, "popular": True},
    {"id": "cat-14", "name": "Bebida de Avena sin azúcares", "categoryId": "lacteos-huevos", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.05, "popular": False},
    {"id": "cat-15", "name": "Hummus de garbanzos clásico", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.45, "popular": True},
    {"id": "cat-16", "name": "Guacamole fresco 95% aguacate", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.99, "popular": True},
    {"id": "cat-17", "name": "Aceite de Oliva Virgen Extra 1L", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "litro", "typicalPrice": 4.70, "popular": True},
    {"id": "cat-18", "name": "Atún claro en aceite de oliva (Pack 6)", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 4.90, "popular": True},
    {"id": "cat-19", "name": "Arroz redondo 1kg", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.15, "popular": False},
    {"id": "cat-20", "name": "Pasta Espaguetis finos 500g", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 0.89, "popular": False},
    {"id": "cat-21", "name": "Tomate frito receta artesana", "categoryId": "despensa-conservas", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.40, "popular": True},
    {"id": "cat-22", "name": "Anacardos tostados sin sal", "categoryId": "aperitivos-dulces", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 2.70, "popular": False},
    {"id": "cat-23", "name": "Chocolate negro 85% cacao", "categoryId": "aperitivos-dulces", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.25, "popular": True},
    {"id": "cat-24", "name": "Pechuga de pollo fileteada corte fino", "categoryId": "carne", "brand": "Hacendado", "defaultUnit": "bandeja", "typicalPrice": 4.80, "popular": True},
    {"id": "cat-25", "name": "Carne picada mixta vacuno/cerdo", "categoryId": "carne", "brand": "Hacendado", "defaultUnit": "bandeja", "typicalPrice": 4.10, "popular": False},
    {"id": "cat-26", "name": "Lomos de Salmón fresco sin espinas", "categoryId": "pescado", "brand": "General", "defaultUnit": "bandeja", "typicalPrice": 6.50, "popular": True},
    {"id": "cat-27", "name": "Jamón Serrano Gran Reserva cortado", "categoryId": "charcuteria-quesos", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 2.65, "popular": True},
    {"id": "cat-28", "name": "Helado Polvito Hacendado", "categoryId": "congelados", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 2.95, "popular": True},
    {"id": "cat-29", "name": "Pizza Jamón y Queso Masa Fina", "categoryId": "congelados", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 2.60, "popular": False},
    {"id": "cat-30", "name": "Salteado de verduras campestre", "categoryId": "congelados", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 1.45, "popular": False},
    {"id": "cat-31", "name": "Detergente líquido Marsella Bosque Verde", "categoryId": "limpieza", "brand": "Bosque Verde", "defaultUnit": "ud", "typicalPrice": 4.10, "popular": True},
    {"id": "cat-32", "name": "Friegasuelos Perfumado Pino", "categoryId": "limpieza", "brand": "Bosque Verde", "defaultUnit": "ud", "typicalPrice": 1.15, "popular": True},
    {"id": "cat-33", "name": "Papel de cocina doble capa", "categoryId": "limpieza", "brand": "Bosque Verde", "defaultUnit": "pack", "typicalPrice": 2.40, "popular": False},
    {"id": "cat-34", "name": "Pastillas lavavajillas Todo en 1", "categoryId": "limpieza", "brand": "Bosque Verde", "defaultUnit": "pack", "typicalPrice": 3.85, "popular": False},
    {"id": "cat-35", "name": "Gel de Baño Aceite de Argán", "categoryId": "perfumeria", "brand": "Deliplus", "defaultUnit": "ud", "typicalPrice": 1.50, "popular": True},
    {"id": "cat-36", "name": "Crema Hidratante Facial Hidra-Sensitive", "categoryId": "perfumeria", "brand": "Deliplus", "defaultUnit": "ud", "typicalPrice": 4.50, "popular": False},
    {"id": "cat-37", "name": "Toallitas húmedas para bebés", "categoryId": "perfumeria", "brand": "Deliplus", "defaultUnit": "pack", "typicalPrice": 1.35, "popular": False},
    {"id": "cat-38", "name": "Zumo de naranja recién exprimido 500ml", "categoryId": "bebidas", "brand": "Hacendado", "defaultUnit": "ud", "typicalPrice": 2.10, "popular": True},
    {"id": "cat-39", "name": "Pack Agua Mineral Natural 6x1.5L", "categoryId": "bebidas", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 2.22, "popular": True},
    {"id": "cat-40", "name": "Cerveza Doble Malta Falke 1925", "categoryId": "bebidas", "brand": "Hacendado", "defaultUnit": "pack", "typicalPrice": 3.60, "popular": False}
]

INITIAL_SAMPLE_ITEMS = [
    {
        "id": "init-1",
        "name": "Hummus de garbanzos clásico",
        "categoryId": "despensa-conservas",
        "brand": "Hacendado",
        "quantity": 2.0,
        "unit": "ud",
        "estimatedPrice": 1.45,
        "notes": "Para picar con zanahorias",
        "completed": False,
        "priority": "alta"
    },
    {
        "id": "init-2",
        "name": "Plátano de Canarias",
        "categoryId": "fruta-verdura",
        "brand": "General",
        "quantity": 1.5,
        "unit": "kg",
        "estimatedPrice": 1.95,
        "notes": "Que no estén muy verdes",
        "completed": False,
        "priority": "media"
    },
    {
        "id": "init-3",
        "name": "Yogur +Proteínas Arándanos 0%",
        "categoryId": "lacteos-huevos",
        "brand": "Hacendado",
        "quantity": 1.0,
        "unit": "pack",
        "estimatedPrice": 1.60,
        "completed": True,
        "priority": "media"
    },
    {
        "id": "init-4",
        "name": "Detergente líquido Marsella",
        "categoryId": "limpieza",
        "brand": "Bosque Verde",
        "quantity": 1.0,
        "unit": "ud",
        "estimatedPrice": 4.10,
        "notes": "Bote grande azul",
        "completed": False,
        "priority": "alta"
    },
    {
        "id": "init-5",
        "name": "Lomos de Salmón fresco",
        "categoryId": "pescado",
        "brand": "General",
        "quantity": 2.0,
        "unit": "bandeja",
        "estimatedPrice": 6.50,
        "completed": False,
        "priority": "media"
    }
]
